package com.company.intranet.onboarding;

public enum OnboardingTask {
    CREATE_CV,
    NETLER_MAIL,
    BIRTHDAY_IN_SLACK,
    SLACK_INVITATION,
    FORTNOX_ADD_USER,
    FORTNOX_RECEIPT_GROUP,
    SLACK_WELCOME_MESSAGE,
    SLACK_PROFILE_PHOTO,
    SEND_WELCOME_LETTER,
    REQUEST_BANK_DETAILS,
    NOTIFY_PAYROLL,
    SETUP_PENSION
}
